### ISSUE TITLE
How to properly handle configuration change?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [L4Digital/RxLoader#2]
Currently, the sample doesn't work well, as it has the workaround of not creating the loader in onCreate again, because it's not called at all, due to a manifest flag:

            android:configChanges="keyboardHidden|orientation|screenSize"

Removing this, I see the sample doesn't even show the data after I change the orientation.
That's even though with a normal loader, it would continue from where it started, and bind to the data when finished.

**Comment by randr0id** [comment]
Had to change `initLoader` to `restartLoader`. Fixed in commit 6606f5a.

**Comment by AndroidDeveloperLB** [comment]
This didn't solve the issue.
Why did you close it?
Now, instead of continuing from where it stopped (or using the final result), it restarts itself every time I change the orientation.
Same as using AsyncTask. You run something, and ditch it when orientation changed...

The point of using a Loader, is to continue the work even after configuration change:
https://developer.android.com/guide/components/loaders.html

![image](https://user-images.githubusercontent.com/5357526/32200428-3d4c05ea-bdda-11e7-9809-e45d914c9c21.png)

**Comment by randr0id** [comment]
This is the correct behavior. By restarting the loader, it re-emits the same data as the when first initialized. The current example doesn't illustrate this well, but if you add a random string to the array that's emitted by the Observable you will see that the first random value emitted is the same that's emitted after an orientation change.

Example, try adding a `new Random().nextFloat()` to the existing array:
~~~java
private static final String[] sVersionNames = new String[]{new Random().nextFloat() + "",
        "Cupcake", "Donut", "Eclair", "Froyo", "Gingerbread", "Honeycomb", "Ice Cream Sandwich",
        "Jelly Bean", "KitKat", "Lollipop", "Marshmallow", "Nougat"
};
~~~

The Observable in this example simply emits a value from the array every half second. You can create a new Observable to emit a different data type, and observe that RxLoader maintains the original Observable. The original data is remitted on a new subscription because the `RxLoaderCallbacks` class uses a [BehaviorProcessor](http://reactivex.io/RxJava/javadoc/io/reactivex/processors/BehaviorProcessor.html) to emit the most recent item.

**Comment by AndroidDeveloperLB** [comment]
No, it's the wrong behavior. It doesn't make sense to restart the loader after each time the Activity gets created. 
Read the docs I've sent you.  Here's more:
https://google-developer-training.gitbooks.io/android-developer-fundamentals-course-concepts/content/en/Unit%203/71c_asynctask_and_asynctaskloader_md.html
![image](https://user-images.githubusercontent.com/5357526/32212712-d1771a7a-be20-11e7-90e7-f9361ca1a721.png)
https://medium.com/google-developers/making-loading-data-on-android-lifecycle-aware-897e12760832
![image](https://user-images.githubusercontent.com/5357526/32212783-21a42b1e-be21-11e7-9fa8-e0431d576efc.png)

You can also try out samples of using loaders, or watch videos about it. Here's one by Google:
https://www.youtube.com/watch?v=s4eAtMHU5gI
A sample by Google (though you need to change the fragment to an Activity, or use setRetainInstance, because the fragment there get re-created) :
https://developer.android.com/reference/android/content/AsyncTaskLoader.html

Upon orientation change, the work that the loader does - shouldn't get restarted. It should continue from where it started. Nothing here should stop it. If it finished before changing orientation, it should show the new result in an instant.
Loaders allow us to continue using what they do after orientation change. That's why if I call "initLoader", I will still get the result of the previous one in onLoadFinished . I will get it in an instant if it was already finished, or a part of the time in case it did partial work.
That's also why I can call getLoader(), to have the loader in a reference and check some things on it if needed (or if I added some fields/functions for me to use in it).

The way you did it now, it's working the same way as AsyncTask, not like Loader, which means it loses the whole point of using a Loader. 
You are losing the whole point of using a Loader, which is to overcome the limitations of AsyncTask, when it comes to configuration change.

Suppose in your sample, the text you get is from the server. It loaded "Cupcake", "Donut", "Eclair" , and now the user changed the orientation. Now it will load them again. Why access the server again, if this partial result was already received, and not just continue working on the rest of the strings...

Your original code, with the android:configChanges flags, was seem to work well, but that's actually not using the loader's purpose. It just avoided re-creating the Activity, so the loader just kept alive because the Activity won't be destroyed upon orientation change.

**Comment by randr0id** [comment]
I agree that `initLoader` should be supported to allow continuing the observable stream or emitting the most recent item. The `restartLoader` behavior should continue to re-subscribe to the observable.

I'm working on a solution for this that should be pushed this week.

**Comment by randr0id** [comment]
Fixed in commit 5d693d9. Scheduled for release in 2.1.0 (1.1.0 for rx1)

**Comment by AndroidDeveloperLB** [comment]
How did you fix it?

**Comment by randr0id** [comment]
Basically had to reset the data that's saved in LoaderCallbacks by calling `deliverResult(mDataCache)` after signaling `onComplete()` by sending a `null` value. Also had to remove null check in `onLoadFinished()` when determining if the observable terminated.
